version: '2'
services:
  # proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: workout-manager-nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   ports:
  #     - "80:80"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  users:
    build: ./services/users
    depends_on:
      - db
    container_name: users-service
    ports:
      - '5050:5050'
